// generated by @ng-toolkit/universal
const port = process.env.PORT || 4001;
// const port = process.env.PORT || 7004;

const server = require('./dist/server/main');

server.app.listen(port, () => {
    console.log("Listening on: http://localhost:" + port);
});
